services:
  backend:
    build: .
    container_name: collegehop-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:15
    container_name: collegehop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: college_hop
      POSTGRES_PASSWORD: college_hop
      POSTGRES_DB: college_hop
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
